name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install minimal deps for tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Env info
        run: |
          python -V
          python -c "import fastapi, pydantic, httpx; print('fastapi', fastapi.__version__, 'pydantic', pydantic.__version__, 'httpx', httpx.__version__)"
      - name: Lint (ruff)
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        run: ruff check . || echo 'ruff warnings ignored on PRs'
      - name: Tests (pytest)
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        run: pytest -q
      - name: Coverage (generate)
        run: |
          pip install coverage
          coverage run -m pytest -q
          coverage xml -o coverage.xml
      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
      - name: Vulnerability scan (pip-audit, non-blocking)
        run: pip-audit -r requirements.txt || true
