name: CI
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:

- name: Write build metadata
  run: |
    echo "{"tag":"${GIT_TAG}","sha":"${GIT_SHA}"}" > api/buildmeta.json
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi pydantic requests httpx starlette
      - name: Lint (quick)
        run: python - <<'PY'
print("lint placeholder (ruff could go here)")
PY
      - name: Smoke (in-process)
        run: python tests/smoke_api.py
