name: CI
on:
  push:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff pip-audit
      - name: Lint (ruff)
        run: ruff check .
      - name: Tests (pytest)
        run: pytest -q
      - name: Vulnerability scan (pip-audit)
        run: pip-audit -r requirements.txt || true
