name: CI
on:
  push:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff pip-audit
      - name: Env info
        run: |
          python -V
          python -c "import sys; print('site-packages:', sys.path)"
          python -c "import fastapi, pydantic; print('fastapi', fastapi.__version__, 'pydantic', pydantic.__version__)"
      - name: Lint (ruff, non-blocking)
        run: ruff check . || echo 'ruff warnings ignored for now'
      - name: Tests (pytest)
        run: pytest -q
      - name: Vulnerability scan (pip-audit, non-blocking)
        run: pip-audit -r requirements.txt || true
