name: API smoke

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi pydantic requests httpx starlette

      - name: Run smoke tests (in-process)
        run: python tests/smoke_api.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-smoke
          path: |
            api_test_report.json
            api_test_report.junit.xml
